# Copyright (c) 2018-2019 Bitwise IO, Inc.
# Licensed under Creative Commons Attribution 4.0 International License
# https://creativecommons.org/licenses/by/4.0/
version: "2.1"

services:
  grid-docs-jekyll:
    build:
      dockerfile: docker/jekyll.dockerfile
      context: .
    image: grid-docs-jekyll
    container_name: grid-docs-jekyll
    working_dir: /srv/jekyll/
    ports:
      - 4000:4000
    volumes:
      - $PWD:/srv/jekyll
    environment:
      - JEKYLL_ENV=${JEKYLL_ENV}
    entrypoint:  |
      bash -c "
        rm -rf  _site
        jekyll serve --config ./_config.yml
      "

  grid-docs-redoc-0-1:
    container_name: grid-docs-redoc-0-1
    image: grid-docs-redoc
    build:
      dockerfile: docker/grid-docs-redoc
      context: .
    ports:
      - 4001:4001
    volumes:
      - .:/project
    entrypoint: |
      bash -c "
        cd /project/docs/0.1/references/api
        redoc-cli serve openapi.yaml -w -p 4001
      "

  grid-docs-apache:
    container_name: grid-docs-apache
    image: grid-docs-apache
    build:
      dockerfile: docker/grid-docs-apache
      context: .
    ports:
      - 8080:80
    volumes:
      - .:/project

  grid-docs-schemaspy:
    container_name: grid-docs-schemaspy
    image: grid-docs-schemaspy
    build:
      context: .
      dockerfile: docker/schemaspy/Dockerfile
    environment:
      HOST: db
      PORT: 5432
      DATABASE: grid
      USER: grid
      PASSWORD: grid_example
    depends_on:
      - db
    volumes:
      - ./db:/output

  db:
    image: postgres
    container_name: db
    hostname: db
    restart: always
    expose:
      - 5432
    environment:
      POSTGRES_USER: grid
      POSTGRES_PASSWORD: grid_example
      POSTGRES_DB: grid

  # gridd:
  #   image: hyperledger/gridd:nightly
  #   container_name: gridd
  #   hostname: gridd
  #   volumes:
  #     - contracts:/usr/share/scar
  #     - gridd:/etc/grid/keys
  #   expose:
  #     - 8080
  #   ports:
  #     - "8088:8080"
  #   environment:
  #     GRID_DAEMON_KEY: "alpha-agent"
  #     GRID_DAEMON_ENDPOINT: "http://gridd:8088"
  #   entrypoint: |
  #     bash -c "
  #       # we need to wait for the db to have started.
  #       until PGPASSWORD=grid_example psql -h db -U grid -c '\q' > /dev/null 2>&1; do
  #           >&2 echo \"Database is unavailable - sleeping\"
  #           sleep 1
  #       done
  #       # grid -vv admin keygen --skip && \
  #       grid -vv database migrate \
  #           --database-url postgres://grid:grid_example@db/grid
  #       # gridd -vv -b 0.0.0.0:8088 -C splinter:http://splinterd:8085 \
  #       #     --database-url postgres://grid:grid_example@db/grid
  #       # java -jar schemaspy/schemaSpy.jar \
  #       #   -t pgsql11 -host $HOST -port $PORT \
  #       #   -db $DATABASE -u $USER -p $PASSWORD -o /output \
  #       #   -dp /org/schemaspy/drivers/postgresql-42.1.1.jre7.jar
  #     "
