#!/bin/bash

until PGPASSWORD=$PASSWORD psql -h $HOST -d $DATABASE -U $USER -c '\q'; do
  >&2 echo "Database is unavailable - sleeping"
  sleep 1
done

java -jar schemaspy/schemaSpy.jar \
    -t pgsql11 -host $HOST -port $PORT \
    -db $DATABASE -u $USER -p $PASSWORD -o /output \
    -dp /org/schemaspy/drivers/postgresql-42.1.1.jre7.jar
